"""updating db

Revision ID: e1cd938e8442
Revises: f564877e89ed
Create Date: 2023-12-10 13:08:45.208747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cd938e8442'
down_revision = 'f564877e89ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
